version: 2

tag-pattern: &tag-pattern
  only: /^v\d+\.\d+\.\d+$/

jobs:
  test:
    working_directory: ~/rn-salesforce-chat
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: yarn test --maxWorkers=2

  publish:
    working_directory: ~/rn-salesforce-chat
    docker:
      - image: circleci/node:11.10.1

    steps:
      - checkout

      - run:
          name: Authenticate npm with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > /home/circleci/rn-salesforce-chat/.npmrc

      - run:
          name: Install project level dependencies
          command: yarn install

      - run:
          name: Publish to npm
          command: npm publish --access public

workflows:
  version: 2
  general:
    jobs:
      - test
      - publish:
          context: org-global
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              <<: *tag-pattern
