platform :ios, '12'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RNSalesforceChat' do

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  # salesforce chat pod
  pod 'ServiceSDK/Chat', '234.1.0'

  use_native_modules!

  post_install do |installer|
    react_native_post_install(installer)
  end
end